---
- hosts: "{{ host_variable }}"
  vars:
    ansible_user: "mousse"
    ansible_port: 480
    nodejs_version: "23.8.0"
    erlang_version: "27.2.3"
    elixir_version: "1.18.2-otp-27"

  tasks:
    - name: Install latest NodeJS
      shell: |
        source ~/.zshrc
        $HOME/.asdf/asdf install nodejs {{ nodejs_version }}
        $HOME/.asdf/asdf global nodejs {{ nodejs_version }}
      args:
        executable: /bin/zsh
        creates: "{{ ansible_env.HOME }}/.asdf/installs/nodejs/{{ nodejs_version }}"

    - name: Install Erlang
      shell: |
        source ~/.zshrc
        $HOME/.asdf/asdf install erlang {{ erlang_version }}
        $HOME/.asdf/asdf global erlang {{ erlang_version }}
      args:
        executable: /bin/zsh
        creates: "{{ ansible_env.HOME }}/.asdf/installs/erlang/{{ erlang_version }}"

    - name: Install Elixir
      shell: |
        source ~/.zshrc
        $HOME/.asdf/asdf install elixir {{ elixir_version }}
        $HOME/.asdf/asdf global elixir {{ elixir_version }}
      args:
        executable: /bin/zsh
        creates: "{{ ansible_env.HOME }}/.asdf/installs/elixir/{{ elixir_version }}"

    # Set global versions and create .tool-versions file
    - name: Create .tool-versions file
      copy:
        dest: "{{ ansible_env.HOME }}/.tool-versions"
        content: |
          nodejs {{ nodejs_version }}
          erlang {{ erlang_version }}
          elixir {{ elixir_version }}

    # Install Hex and Rebar for Elixir
    - name: Install Hex and Rebar
      shell: |
        source ~/.zshrc
        mix local.hex --force
        mix local.rebar --force
      args:
        executable: /bin/zsh
