---
- hosts: "{{ host_variable }}"
  vars:
    ansible_user: "mousse"
    ansible_port: 480

  pre_tasks:
    - name: Install additional packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - postgresql-contrib
        - python3-psycopg2
      become: yes
      become_user: root
      become_method: sudo

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data
      become: yes
      become_user: root
      become_method: sudo

    # - name: "Initialize PostgreSQL"
    #   shell: "postgresql-setup initdb"
    #   when: not postgres_data.stat.exists
    #   become: yes
    #   become_user: root
    #   become_method: sudo
 
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql
      become: yes
      become_user: root
      become_method: sudo

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted

